version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/docker/www:/usr/share/nginx/html'
      - '/docker/config:/etc/nginx/config'
      - '/docker/config/nginx.conf:/etc/nginx/nginx.conf'
      - '/docker/cert:/etc/nginx/cert'
  node:
    image: node
    container_name: node
    ports:
      - '3600:3600'
    volumes:
      - '/docker:/usr/share/apps'
      - ./logs:/app/logs
    external_links:
      - mysql:mysql
      - redis:redis
    stdin_open: true
    tty: true
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass 你的密码
    stdin_open: true
    tty: true
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=你的密码'
    stdin_open: true
    tty: true
