/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoadingAnimation: typeof import('./../src/components/loading-animation.vue')['default']
    LoadingMore: typeof import('./../src/components/loading-more.vue')['default']
    LoadingPage: typeof import('./../src/components/loading-page.vue')['default']
    NullPlaceholder: typeof import('./../src/components/null-placeholder.vue')['default']
    ResponsiveNotice: typeof import('./../src/components/responsive-notice.vue')['default']
    ResponsiveSwiper: typeof import('./../src/components/responsive-swiper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgImg: typeof import('./../src/components/svg-img.vue')['default']
    ViewCell: typeof import('./../src/components/view-cell.vue')['default']
    ViewMask: typeof import('./../src/components/view-mask.vue')['default']
    ViewModal: typeof import('./../src/components/view-modal.vue')['default']
    ViewTag: typeof import('./../src/components/view-tag.vue')['default']
  }
}
