/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CCaptcha: typeof import('./../src/components/c-captcha.vue')['default']
    CSms: typeof import('./../src/components/c-sms.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAntIcon: typeof import('./../src/components/u-ant-icon.vue')['default']
    UcAntIcon: typeof import('../src/components/u-ant-icon.vue')['default']
    ULayoutForm: typeof import('./../src/components/u-layout-form.vue')['default']
    ULayoutList: typeof import('./../src/components/u-layout-list.vue')['default']
  }
}
