/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CCaptcha: typeof import('./../src/components/c-captcha.vue')['default']
    Components: typeof import('./../src/components/index.vue')['default']
    CScreenBg: typeof import('./../src/components/c-screen-bg.vue')['default']
    CSms: typeof import('./../src/components/c-sms.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
